/*
Player groups configuration file
---------------------------------

Custom configuration for ragna server with player commands
*/

groups: (
{
	id: 0 /* group 0 is the default group for every new account */
	name: "Player"
	level: 0
	inherit: ( /*empty list*/ )
	commands: {
		/* Custom player commands */
		commands: true
		help: true
		rates: true
		showdelay: true
		exp: true
		mobinfo: true
		iteminfo: true
		whodrops: true
		servertime: true
		jailtime: true
		showexp: true
		showzeny: true
		whereis: true
		autotrade: true
		noks: true
		itemlist: true
		refresh: true
		noask: true
		autoloot: true
		alootid: true
		autoloottype: true
	}
	permissions: {
		/* without this basic permissions regular players could not trade or party */
		can_trade: true
		can_party: true
		attendance: true
	}
},
{
	id: 99
	name: "Admin"
	level: 99
	inherit: ( /*empty list*/ )
	commands: {
		/* not necessary due to all_commands: true */
	}
	log_commands: true
	permissions: {
		can_trade: true
		can_party: true
		command_enable: true
		all_skill: false
		all_equipment: false
		skill_unconditional: false
		use_check: true
		use_changemaptype: true
		all_commands: true
		channel_admin: true
		can_trade_bounded: true
		item_unconditional: false
		bypass_stat_onclone: true
		bypass_max_stat: true
		/* all_permission: true */
	}
}
)
